baseURL = "http://laohanlinux.github.io/"
languageCode = "en-us"
title = "Welcome to Rg Home"
theme = "LeaveIt"

[params]
home_mode = "post" # post or other

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
